/* ==============================================
   km_plot.sas
   Generate FDA-standard Kaplan-Meier plots
   
   Input:  data/adtte.csv
   Output: output/km_plot_TTDEATH.pdf
           output/km_plot_TTDEATH.png
           output/km_plot_TTDEATH.rtf
   
   Equivalent of: km_plot.R
   ============================================== */

/* ---- Import ADTTE dataset ---- */
proc import datafile="data/adtte.csv"
  out=adtte dbms=csv replace;
  guessingrows=500;
run;

/* ---- Subset TTDEATH ---- */
data ttdeath;
  set adtte;
  where PARAMCD = "TTDEATH";
  event = (CNSR = 0);  /* 1 = event, 0 = censored */
  AVAL_N = AVAL;
  label AVAL_N = "Analysis Value (Days)"
        event  = "Event Indicator";
run;

proc sort data=ttdeath;
  by TRT01P;
run;

/* ---- Log-rank test ---- */
ods output LogRank=logrank;
proc lifetest data=ttdeath;
  time AVAL_N * CNSR(1);
  strata TRT01P / test=logrank;
run;

data _null_;
  set logrank;
  where Test = "Log-Rank";
  pval = ProbChiSq;
  length pval_fmt $20;
  if pval < 0.0001 then pval_fmt = "p < 0.0001";
  else pval_fmt = cats("p = ", put(round(pval, 0.0001), 8.4));
  call symputx("pval_fmt", pval_fmt);
  call symputx("pval_num", pval);
run;

%put Log-rank test: &pval_fmt;

/* ---- Kaplan-Meier survival estimates for plotting ---- */
ods output ProductLimitEstimates=kmest;
proc lifetest data=ttdeath maxtime=365;
  time AVAL_N * CNSR(1);
  strata TRT01P;
run;

/* ---- Baseline covariates for plot annotations ---- */
proc sql noprint;
  select distinct STUDYID into :study_label
  from ttdeath;
quit;

/* ---- ODS PDF output ---- */
ods listing close;
ods pdf file="output/km_plot_TTDEATH.pdf"
  style=journal
  dpi=300;

ods graphics / reset width=8in height=6.5in
  imagename="km_plot_TTDEATH"
  imagefmt=pdf;

proc lifetest data=ttdeath plots=survival(cb=all atrisk=0 to 360 by 60 test);
  time AVAL_N * CNSR(1);
  strata TRT01P / test=logrank;
  title1 bold height=12pt "Study &study_label";
  title2 bold height=11pt "Kaplan-Meier Plot of Time to Death";
  title3 height=9pt "Log-rank test: &pval_fmt";
  footnote1 height=8pt italic "Note: + denotes censored observations";
  footnote2 height=7pt "Generated by SAS on &sysdate";
run;
title;
footnote;

ods pdf close;

/* ---- ODS RTF output ---- */
ods rtf file="output/km_plot_TTDEATH.rtf"
  style=journal
  dpi=300;

ods graphics / reset width=8in height=6.5in
  imagename="km_plot_TTDEATH"
  imagefmt=emf;  /* enhanced metafile for better RTF embedding */

proc lifetest data=ttdeath plots=survival(cb=all atrisk=0 to 360 by 60 test);
  time AVAL_N * CNSR(1);
  strata TRT01P / test=logrank;
  title1 bold height=12pt "Study &study_label";
  title2 bold height=11pt "Kaplan-Meier Plot of Time to Death";
  title3 height=9pt "Log-rank test: &pval_fmt";
  footnote1 height=8pt italic "Note: + denotes censored observations";
  footnote2 height=7pt "Generated by SAS on &sysdate";
run;
title;
footnote;

ods rtf close;

/* ---- ODS HTML output for PNG fallback ---- */
ods html file="output/km_plot_TTDEATH.html"
  style=journal
  image_dpi=300;

ods graphics / reset width=8in height=6.5in
  imagename="km_plot_TTDEATH"
  imagefmt=png;

proc lifetest data=ttdeath plots=survival(cb=all atrisk=0 to 360 by 60 test);
  time AVAL_N * CNSR(1);
  strata TRT01P / test=logrank;
  title1 bold height=12pt "Study &study_label";
  title2 bold height=11pt "Kaplan-Meier Plot of Time to Death";
  title3 height=9pt "Log-rank test: &pval_fmt";
  footnote1 height=8pt italic "Note: + denotes censored observations";
  footnote2 height=7pt "Generated by SAS on &sysdate";
run;
title;
footnote;

ods html close;

ods listing;

/* ---- Copy the PNG to output/ ---- */
/* The PNG is created by ODS HTML in the current working directory */
/* Move it to output/ */
/* (SAS 9.4 creates "km_plot_TTDEATH.png" in the current dir by default) */
/* We'll copy it programmatically */
data _null_;
  rc = system("if [ -f km_plot_TTDEATH.png ]; then cp km_plot_TTDEATH.png output/km_plot_TTDEATH.png; fi");
run;

/* ---- Summary statistics ---- */
proc sql;
  title "Median Survival by Arm";
  select TRT01P, count(*) as N, avg(AVAL_N) as Mean_Days format=8.1,
         median(AVAL_N) as Median_Days format=8.1
  from ttdeath
  group by TRT01P;
quit;

title "Log-rank Test Result";
proc print data=logrank noobs label;
  where Test = "Log-Rank";
  var Test ChiSq ProbChiSq;
  label Test = "Test" ChiSq = "Chi-Square" ProbChiSq = "p-value";
run;
title;

/* ---- Clean up work files ---- */
proc datasets lib=work nolist;
  delete adsl adtte ttdeath kmest logrank;
quit;
